- adapters/outbound/urltest.go
目前这个方案比较完善，不过还可能存在一种情况，就是speedTest在tick启动了，然后出现错误了，又会在connErr case中再启动一次。 
1. 之前想过用sync.once只能运行一个speedTest,但是一旦这样，就很难reset了。
2. 如果直接用锁也是可以实现的，不过感觉效率不高。
你再帮忙看下还有什么问题不？
>  Fix: cannot switch when fast is hang in auto mode

- adapters/outbound/socks5.go
`{ name: "socks5", type: "socks5", server: "example.com", port: 443, tls: true, sni: true }`
> Update: add tls, sni options to socks5 outbound adapter

- adapters/outbound/socks5.go
- adapters/outbound/util.go
- adapters/outbound/vmess.go
- component/vmess/vmess.go
启用  client session cache ，配合 server 配置减少 tls 再次握手时间，提高响应速度
> enabled tls session ticket resumption

- proxy/http/server.go
- proxy/listener.go
- proxy/redir/tcp.go
- proxy/socks/tcp.go
测试程序如下：
```golang
package main
import (
"fmt"
"net"
"runtime"
"time"
"github.com/Dreamacro/clash/log"
)
func countGoRoutines() int {
return runtime.NumGoroutine()
}
type listener struct {
Address string
Done    chan<- struct{}
Closed  <-chan struct{}
}
func NewHttpProxy(addr string) (chan<- struct{}, <-chan struct{}, error) {
l, err := net.Listen("tcp", addr)
if err != nil {
return nil, nil, err
}
done := make(chan struct{})
closed := make(chan struct{})
go func() {
log.Infoln("HTTP proxy listening at: %s", addr)
for {
_, err := l.Accept()
if err != nil {
if _, open := <-done; !open {
break
}
continue
}
//go handleConn(c)
}
}()
go func() {
<-done
close(done)
l.Close()
closed <- struct{}{}
fmt.Printf("HTTP proxy close: %s\n", addr)
}()
return done, closed, nil
}
func main() {
for i := 0; i …
```
> Fix: goroutine leak while closing proxy

- tunnel/connection.go
目前有些客户端比较笨，比如php的file_get_contents，他不能主动判断http 的keep-alive，一般的正确做法是，php先获取到content-length,然后判断获取到的内容和content-length一样长，就输出内容，而不是一直等。php 的curl库就会自动判断，所以不会卡住。
但是一般客户端有时会传"connection":"close"的头部，就是说不与服务端保持长连接，这里clash的代理应该也不保持长连接，目前nginx的proxy也是会判断这个头部，然后nginx自动断开长连接.
#60
> Fix: don't keepalive when connection is close

- .gitignore
- Makefile
As many users want to simply download binary they need from the Release page, I add some os/arch pair for router and raspberry pi user.
If I miss some popular platform or some platform is not so popular, please let me know.
Support following os/arch:
- darwin-amd64
- linux-386
- linux-amd64
- linux-armv5
- linux-armv6
- linux-armv7
- linux-armv8
- linux-mips-softfloat
- linux-mips-hardfloat
- linux-mipsle
- linux-mips64
- linux-mips64le
- freebsd-386
- freebsd-amd64
- windows-386
- windows-amd64
> Add more platform to Makefile 

- hub/executor/executor.go
当dns启动失败时没有错误信息，比较难排查是哪里的问题。
输出错误日志便于查询问题。
> Chore: print log when start dns server failed

- adapters/outbound/http.go
nghttpx会检测Host头部，如果没有头部会返回400错误。
测试过程：
1. nghttpx的配置, 运行命令：`sudo nghttpx --conf=nghttpx.conf`
```
frontend=0.0.0.0,8088;no-tls
backend=127.0.0.1,8081;;no-tls;proto=http/1.1
http2-proxy=yes
```
2. 支持connect的[http proxy](https://www.flysnow.org/2016/12/24/golang-http-proxy.html), 编译运行，监听在8081端口，也就是nghttpx的backend对应的端口。
3. clash的配置
```
- { name: "http", type: http, server: 127.0.0.1, port: 8088 }
```
4. 测试命令`curl https://www.baidu.com -x 127.1:7890`
> Fix: return 400 error when connect to nghttpx

- config/config.go
今天在自己写规则的时候，写错了一个字母，然后报错第80条规则错误，但是配置文件里面有很多注释，找了好久才找到。
如果能在错误信息里面直接输出第80条规则，这样查找错误就非常快。
> Chore: print origin rule for finding error easily

- README.md
- adapters/inbound/http.go
- adapters/inbound/https.go
- adapters/inbound/socket.go
- adapters/inbound/util.go
- config/config.go
- constant/metadata.go
- constant/rule.go
- rules/ipcidr.go
- tunnel/tunnel.go
When running Clash in router, I want some of my clients to only go through a part of Clash's rules.
Specifically, I don't want my NAS to go through the GeoIP rule, since I run BT downloads in it. 
With this rule type and some changes in the rule sequence, Clash can be more flexible as a redirector in router.
> Feature: FROM-IP-CIDR rule type

- adapters/inbound/util.go
- dns/client.go
修复 #99
测试命令：
```
curl --socks5-hostname 127.1:7891 http://192.168.123.89
```
修复前日志：
```
INFO[0011] 192.168.123.89 match IPCIDR using Proxy
```
修复后日志：
```
INFO[0011] 192.168.123.89 match IPCIDR using  DIRECT
```
> Fix: parse host is ip when use socks proxy

- README.md
- config/config.go
- add TCP DNS support in DNS config
- log the DNS config parsing error 
fix #126
> support TCP DNS & log the DNS parsing error

- adapters/outbound/shadowsocks.go
- component/v2ray-plugin/websocket.go
我对v2ray-plugin这里，加上了自定义Headers，
```
- name: "ss3"
type: ss
server: server
port: 443
cipher: AEAD_CHACHA20_POLY1305
password: "password"
plugin: v2ray-plugin
plugin-opts:
mode: websocket 
headers: { Host: v2ray.com, AVC: bing.com}
```
> Add Headers setting in ss-v2ray-plugin

- dns/client.go
- dns/server.go
Edited, the original title is "Add TCP DNS server"
- Listen TCP port at the same time
- Add err log for DNS server
In some case, the upstream DNS server will return large DNS response, which is larger than a single UDP package. The UDP response will set the `truncated` flag. Most DNS client will try to get the full response through TCP again.
If clash doesn't implement a TCP DNS service, the following error will happen.
```
dig @127.0.0.1 -p 5353 unpkg.zhimg.com 
;; WARNING: truncated reply from 127.0.0.1@5353(UDP), retrying over TCP
;; WARNING: can't connect to 127.0.0.1@5353(TCP)
;; WARNING: truncated reply from 127.0.0.1@5353(UDP), retrying over TCP
;; WARNING: can't connect to 127.0.0.1@5353(TCP)
;; WARNING: truncated reply from 127.0.0.1@5353(UDP), retrying over TCP
;; WARNING: can't …
```
> Increase UDPSize for DNS and add error log for dns service

- adapters/outbound/selector.go
- config/config.go
the order of proxies and Selector's proxies list are arbitrary, when you have dozens of nodes, it was confusing, I make it the same as the order in the config file and the change will not break up previous versions of web version GUI(http://clash.razord.top). I will create a pull request to clash-dashboard latter.
> make the proxies order the same as the order in config file

- adapters/outbound/urltest.go
The urltest outbound is currently sorting alphabetically which is inconsistent with other outbound types. This is to make it work as expected.
> Use original sequence for urltest group

- Makefile
https://github.com/Dreamacro/clash/issues/136
https://github.com/Dreamacro/clash/issues/239
Add mipsle-softfloat for common router's CPUs like MT7620A and MT7621A
> Feature: add mipsle-softfloat

- dns/resolver.go
还有一个问题：现在的picker是要等多个dns都返回了都返回结果，不是选最快的了。这样在如果我有一个dns服务器不通的时候(比如内网dns),这样会影响整个查询速度
> Fix: use same client

- config/config.go
- config/utils.go
Check whether `ProxyGroups` forms a DAG(directed acyclic graph), and sort ProxyGroup by their inner dependency relation.
Some user wants to keep the original order of `ProxyGroup` in their config file. This PR only deal with one part of it, the loop detection problem.
function `ProxyGroupsDagSort` build a dependency graph using `rawConfig`, and run **Topological Sorting** on that graph. Then sort all `ProxyGroup` . If a loop is detected, throw an error.
> Allow arbitrary order in ProxyGroup, loop detect, and autosort ProxyGroup

- .gitignore
- adapters/outbound/socks5.go
- tunnel/tunnel.go
1. 根据Go命名规则修改了几处`tunnel.go`里的变量
2. UDP连接关闭的同时也关闭TCP连接，防止因为socks服务端不主动断开TCP连接而造成客户端TCP suspend
3.  在.gitignore里增加了两个path，以后改代码就不用每次手动选择忽略了。😂
> Optimize: socks UDP & fix typo

- config/config.go
- config/utils.go
@yichengchen use the `all` array in `GLOBAL` ProxyGroup to sort the `ProxyGroup`s.
This is a brilliant idea and doesn't need something like `Idx` field at all.
> Keep the origional order of ProxyGroups in config file

- adapters/outbound/util.go
In `dialTimeout` function, the last `select` clause(Line 161) wait for **one  the successful dial**, or **failure of both ipv4 and ipv6**
https://github.com/Dreamacro/clash/blob/09917a2a9519d1acd42b2e1b4031d169eb50203e/adapters/outbound/util.go#L159-L176
But startRacer function didn't return the failure of `Dial`
https://github.com/Dreamacro/clash/blob/09917a2a9519d1acd42b2e1b4031d169eb50203e/adapters/outbound/util.go#L143-L145
So, the `dialTimeout` may keep waiting in (Line 161) if both ipv4 and ipv6 are failed to Dial.
> Fix: correct TCP dual stack dial

- adapters/outbound/util.go
- dns/iputil.go
- dns/resolver.go
When an IP address is provided, we should not start the dual-stack dial procedure.
---
Sometimes, when users are connecting remote host with **IP address** through clash
```
curl --socks5-hostname 127.0.0.1:7891 http://224.0.0.0
```
For now, Clash will output one line warning
> WARN[0000] dial DIRECT error: dial tcp6: address 224.0.0.0: no suitable address found 
Because if both `IPv4` and `IPv6` are failed to connect, `dialTimeout` will return the `IPv6` error
https://github.com/Dreamacro/clash/blob/1a8a6d0b5d28161069c23560464be9f1e0eb6fd7/adapters/outbound/util.go#L163-L167
Actually, when users are using IPv4 address, clash should not try to connect with IPv6.
> Skip dual-stack dial when ip address is provided directly

- adapters/inbound/packet.go
- adapters/outbound/shadowsocks.go
- component/fakeip/pool.go
- component/socks5/socks5.go
- constant/adapters.go
- dns/middleware.go
- dns/resolver.go
- proxy/socks/udp.go
- proxy/socks/utils.go
- tunnel/connection.go
- tunnel/tunnel.go
1. [x] Full-cone NAT (fix #403)
2. [x] Auto-scaling udp workers(fix #436)
1. More loose NAT
Add a `WriteFrom` interface allowing outbound to write out packets with sourceIP/sourcePort different from origin target.
Tested on **shadowsocks**(outbound) and **socks5**(inbound), with the help of [go-tun2socks](https://github.com/eycorsican/go-tun2socks)  to create tun interface
(*from* bc81c9f)
<details>
<summary>Logs from go-stun</summary>
```
2019/12/21 20:12:26 Do Test1
2019/12/21 20:12:26 Send To: 216.93.246.18:3478
2019/12/21 20:12:26 Received: {packet nil: false, local: 20.176.71.59:62383, remote: 216.93.246.18:3478, changed: 56.162.98.102:32823, other: <nil>, identical: false}
2019/12/21 20:12:26 Do Test2
2019/12/21 20:12:26 Send To: 216.93.246.18:3478
2019/12/21 20:12:26 Received: …
```
> UDP relay refactor

- dns/resolver.go
日常用下来，即便是国内的域名解析，也偶尔会遇到超过 1s 解析时间的，DNS 出错搞得有点困扰。
参考 man resolv.conf 默认设置是 5s，应该比较合理
```
timeout:n
sets  the amount of time the resolver will wait for a response from a remote name server before retrying the query via a different name server.  Measured in seconds, the default is RES_TIMEOUT (currently 5, see <resolv.h>).  The value for this option is silently capped to 30.```
> Increase DNS timeout

- common/picker/picker.go
- dns/client.go
- dns/resolver.go
- dns/util.go
Clash DNS is designed to pick the first non-nil response from upstream DNS as the response. 
https://github.com/Dreamacro/clash/blob/86d3d77a7f15f8dfc81f68add51cba4f84eb591e/dns/resolver.go#L183-L195
But actually, the picker doesn't work because miekg/dns doesn't respond to context cancel when calling [ExchangeContext](https://github.com/miekg/dns/blob/fbd426fefa88dae28c9ee1349b95c792379a6068/client.go#L400-L415).
Clash should wrap `ExchangeContext` or replace ` elm := fast.Wait()` with `fast.WaitWithoutCancel`
> [Fix] Let ExchangeContext respond to cancel

- tunnel/manager.go
又又又是 Clash for Android (
添加一个清除统计信息的 API (
Clash for Android 启动/关闭 代理不会结束 Clash 进程 (
需要一个 API 来重置统计信息 (
> [Feature] Add Reset Statistic API

- adapters/outbound/base.go
解决url-test时URL重定，Delay无返回
应该可以解决 #411
>  [Fix] Http Redirect

- main.go
I generate clash config with [clash-config-preprocessor](https://github.com/whtsky/clash-config-preprocessor/). Sometimes the generated config file is invalid due to upstream rule-set changes, so it would be nice to have the configuration file test feature built-in.
The cli design is highly influenced by `nginx -t`.
> Feature: add configuration test

- proxy/redir/udp.go
- proxy/redir/utils.go
- tunnel/connection.go
- tunnel/tunnel.go
This pr is inspired by 9010090800663aa0449e88888b9ede8ffb3361b6. It improves UDP NAT behavior for TPROXY(#562).
In `WriteBack` function, the socket should bind to `origDst` only if `origDst` maps to a host(fake-ip or redir-host mode). Otherwise it'll be ok to bind to `addr`(the real source of the UDP packet to write back).
> Fix UDP NAT type for TPROXY

- README.md
- adapters/outbound/base.go
- adapters/outbound/direct.go
- adapters/outbound/http.go
- adapters/outbound/reject.go
- adapters/outbound/shadowsocks.go
- adapters/outbound/snell.go
- adapters/outbound/socks5.go
- adapters/outbound/trojan.go
- adapters/outbound/util.go
- adapters/outbound/vmess.go
- adapters/outboundgroup/fallback.go
- adapters/outboundgroup/loadbalance.go
- adapters/outboundgroup/parser.go
- adapters/outboundgroup/relay.go
- adapters/outboundgroup/selector.go
- adapters/outboundgroup/urltest.go
- adapters/outboundgroup/util.go
- constant/adapters.go
#434
config:
```yaml
proxy-groups:
- name: "relay"
type: relay
proxies:
- http1
- vmess1
- ss1
- ss2
```
traffic:
`clash <-> http1 <-> vmess1 <-> ss1 <-> ss2 <-> Internet`
> [Feature] [TCP only] Support relay (proxy chains)

- tunnel/connection.go
- tunnel/tracker.go
修复 UDP 下载流量重复计算 以及 UDP 上传流量未被 tracker 追踪
> Fix: udp duplicate download traffic & update traffic track

- dns/util.go
DoT with hostname instead of bare IP has never been working. This problem normally would be covered up when multiple DNS servers presented. If only one DoT DNS server with hostname, e.g. "tls://dns.rubyfish.cn:853", the log would show "All DNS requests failed". 
My config:
```yaml
dns:
enhanced-mode: redir-host
listen: 127.0.0.1:7874
enable: true
ipv6: false
default-nameserver:
- 114.114.114.114
nameserver:
- 114.114.114.114
fallback:
- tls://dns.rubyfish.cn:853
fallback-filter:
geoip: true
ipcidr:
- 240.0.0.0/4
- 0.0.0.0/32
```
Adding the following debug logger to `dns/client.go`:
the root problem can be found when `dig @192.168.1.1 www.google.com` (my clash running in x86-64 router):
The problem is obvious, 'miekg/dns' has never been informed the hostname but only a resolved IP. After …
> Fix: dns tcp-tls X509.HostnameError

- dns/middleware.go
修复 部分应用不使用 fake ip nameserver 的问题 (指 `nslookup`
这个 commit 前
```
kr328@2B ~ % nslookup www.baidu.com                                                            :(
;; Got recursion not available from 192.168.0.1, trying next server
Server:		fdb9:2d81:1d2f::1
Address:	fdb9:2d81:1d2f::1#53
Non-authoritative answer:
www.baidu.com	canonical name = www.a.shifen.com.
Name:	www.a.shifen.com
Address: 163.177.151.110
Name:	www.a.shifen.com
Address: 163.177.151.109
;; Got SERVFAIL reply from 192.168.0.1, trying next server
```
后
```
kr328@2B ~ % nslookup www.baidu.com
Server:		192.168.0.1
Address:	192.168.0.1#53
Name:	www.baidu.com
Address: 198.18.0.6
```
`nslookup` 版本
```
bind-tools 9.16.2-1
```
> Fix: dns return success & recursion available if fake ip enabled

- adapters/outbound/direct.go
按照目前的逻辑 一旦在规则匹配时 存在 DNS 解析行为 metadata.DstIP 必定不为空
在原先的逻辑下 DstIP 不为空时 会导致 双栈 Dial 逻辑失效
不过这样的改法可能会导致 最终 Dial 结果 与 规则匹配不一致 (
> Fix: re-resolve dns on direct dial

- common/cache/lrucache.go
- common/cache/lrucache_test.go
- dns/resolver.go
- dns/util.go
This PR replaces the existing DNS cache with LRU Cache and thus can achieve optimistic DNS.
When a DNS query comes to clash, if there is an expired msg in cache match the query, clash will return the expired msg and start to fetch the newer response from upstream **async**.
When mapping(redir-host/fake-ip) is enabled, when request without Host but IP comes to clash, clash will do IP-to-Host checking using this IP in LRU Cache. This procedure **will not** affect the TTL of the corresponding DNS messages.
- What TTL should clash reply when an expired DNS msg return?
- How large should the cache capacity be set?
- Should cache size and optimistic DNS be configurable?
> [Feature] DNS: employ LruCache for optimistic DNS

- README.md
- adapters/outbound/base.go
- adapters/outboundgroup/fallback.go
- adapters/outboundgroup/loadbalance.go
- adapters/outboundgroup/relay.go
- adapters/outboundgroup/selector.go
- adapters/outboundgroup/urltest.go
- constant/adapters.go
```yaml
proxy-groups:
- name: "select"
type: select
proxies:
- ss1
- ss2
- name: "relay"
type: relay
proxies:
- select
- vmess1
```
- Healthchecks don't follow the proxy chains.
> Feature: support proxy-group in relay

- dns/resolver.go
域名匹配到 fake-ip-filter 时 回滚到 redir-host 模式
能够让 域名规则 在 命中 fake-ip-filter 时 生效
> [Future] fallback to redir-host if host match fake-ip-filter

- component/trie/domain.go
- component/trie/domain_test.go
假设 trie 已插入以下域名
```
"+.stun.*.*"
"+.stun.*.*.*"
"+.stun.*.*.*.*"
"lens.l.google.com"
"stun.l.google.com"
"*.n.n.srv.nintendo.net"
```
在旧逻辑上 匹配域名 `global.stun.website.com` 时
会因为 com 进入 `lens.l.google.com/stun.l.google.com` 的节点 接下来在 和 `google` 匹配时失败 返回 nil
> [Fix] trie: should backtrack to parent if match fail

- tunnel/tunnel.go
修复 https://github.com/Dreamacro/clash/commit/78c30341581ae6a4e0408a2682dbd96a44b50795 改变名称但未改变逻辑
> Fix: invert should resolve ip

- component/ssr/protocol/auth_aes128_md5.go
- component/ssr/protocol/protocol.go
尝试修复#879 
无法复现该问题。翻看了一下libev，遗漏了对checksum的校验([`91f4d7c`](https://github.com/Dreamacro/clash/commit/91f4d7c66ea672fa0ce1540951feefb44b38295b),但无法确定是否是由于这个造成的)；对`pos`和`length - 4`的大小进行了一个判断([`5f9a69f`](https://github.com/Dreamacro/clash/commit/5f9a69fdc8947abde157717ea923a5277d1a9c9d),libev中没有该部分代码)，避免出现crash，如果觉得没必要可以不合并这个commit。
> Try fix crash

- component/ssr/protocol/auth_aes128_md5.go
Fix #894 
抱歉，写 #882 的时候可能脑子不太清醒，用错了变量。
麻烦check一下[python源码](https://github.com/shadowsocksr-backup/shadowsocksr/blob/manyuser/shadowsocks/obfsplugin/auth.py#L611,L614)和[libev源码](https://github.com/shadowsocksr-backup/shadowsocksr-libev/blob/master/src/obfs/auth.c#L894,L903)，避免再次出错。
> Fix: use the wrong variable

- rules/process_darwin.go
- rules/process_freebsd_amd64.go
缓存 PROCESS-NAME 解析失败的结果 (第一次失败了 接下来也几乎不会成功
> Feature: Cache failed result of resolve process name

- rules/process_darwin.go
- rules/process_freebsd_amd64.go
This PR aims to fix https://github.com/Dreamacro/clash/issues/879#issuecomment-685732139
By https://github.com/golang/go/blob/master/src/syscall/syscall_bsd.go#L473, the result of `sysctl` will be trimmed.
> Fix: potential PCB buffer overflow on bsd systems

- rules/process_freebsd_amd64.go
FreeBSD 11 and 12 have different PCB layouts. Now class will check the major version while initialization.
> Fix: PROCESS-NAME on FreeBSD 11.x

- adapters/outbound/vmess.go
- component/vmess/h2.go
- component/vmess/tls.go
- go.sum
Support HTTP/2 transport for VMess.
```yaml
proxies:
- name: Proxy
type: vmess
server: 1.14.5.14
port: 443
uuid: 433a65e8-6ab0-49cb-98b6-bde1605f000a
alterId: 15
cipher: auto
network: h2
h2-opts:
host:
- http.example.com
- http-alt.example.com
path: /
tls: true
```
The client will reuse existing TLS connection by `StreamTLSConn` (while setting ALPN to be `h2`), send HTTP/2 requests, and perform Read/Write on the connection created. It will randomly choose a host for HTTP/2 `:authority` header from `h2-opts.host`.
> VMess HTTP/2 transport support

- config/config.go
- dns/filters.go
- dns/resolver.go
- hub/executor/executor.go
Sometimes domain (e.g. google.com) is resolved to a random IP address in China, the current clash will return the IP from standard nameservers directly, which is not right.
This new config is to always return the result of fallback nameservers if domain or domain suffix is matched.
Fallback Config Example:
```
fallback-filter:
geoip: true
ipcidr:
- 240.0.0.0/4
- 0.0.0.0/32
domain:
- '+.google.com'
- '+.facebook.com'
- '+.youtube.com'
```
> Feature: support domain in fallback filter

- component/process/process_windows.go
Windows binds an unbound UDP socket to 0.0.0.0/:: while first `sendto`.
So we give unspecific addresses a try for UDP sessions.
> Fix: PROCESS-NAME rule for UDP sessions on Windows

- adapters/provider/fetcher.go
使用rule-providers，规则自动更新时，如果是规则来源是File类型，会意外的触发一次IO写操作，这里进行了修复。
> Fix: unnecessary write operation on provider

- common/net/io.go
- common/wrapper/io.go
- tunnel/connection.go
考虑这样的情况
在传入参数有任意一个是 *net.TCPConn (当然 rightConn 不可能是 TCP 毕竟有 TcpTracker
https://github.com/Dreamacro/clash/blob/3600077f3b6997c7b9e7a42a69afde6b17a5e5b1/tunnel/connection.go#L134-L151
调用到
```go
func CopyBuffer(dst Writer, src Reader, buf []byte) (written int64, err error) {
if buf != nil && len(buf) == 0 {
panic("empty buffer in CopyBuffer")
}
return copyBuffer(dst, src, buf)
}
```
再往下
```go
func copyBuffer(dst Writer, src Reader, buf []byte) (written int64, err error) {
// If the reader has a WriteTo method, use it to do the copy.
// Avoids an allocation and a copy.
if wt, ok := src.(WriterTo); ok {
return wt.WriteTo(dst)
}
// Similarly, if the writer has a ReadFrom method, use it to do the copy.
if rt, ok := dst.(ReaderFrom); ok {
return rt.ReadFrom(src) // 到此为止
}
// Copy 
......
}
``` …
> Fix: wrap net.Conn to avoid using *net.TCPConn.(ReadFrom)

- adapters/provider/fetcher.go
略微减少 provider 初始化时写入 (
同时让文件的修改时间更加有意义 (而不是每次重载配置文件就刷新一遍
> Chore: reduce provider write

- .github/workflows/go.yml
- Makefile
Go 1.16 adds support for darwin arm64 and is now released.
> Add m1 mac support

- tunnel/connection.go
实际使用里有些依赖UDP的协议只会发送但不一定会有回复（比如有些心跳包），所以UDP的会话超时机制应该取决于两侧是否有活跃的包传输，而不是仅靠一侧的readfrom来实现。
> Fix: reset udp timeout after sending each packet

- tunnel/tunnel.go
防止出现`metadata.AddrType=C.AtypDomainName`而`metadata.Host=""`的情况
> Fix: set metadata.AddrType if host is ip string after remove host

- config/initial.go
Since ``mixed-port`` support both ``socks5`` and ``http`` inbound, there is no need for a initial config to accept ``socks5`` only
> [New Feature] Use mixed-port instead of port

- component/vmess/aead.go
Android Clash
使用安卓 clash 进行 WhatsApp 通话时，v2ray / xray 服务端经常会出现数据包解密出错的情况，服务端默认行为是丢弃此包，不断开连接，所以这个问题可能很久都没人发现。
使用基于 v2ray / xray 或其它实现的客户端暂时没有发现此问题。
通过 debug 服务端，发现 clash 客户端发来的包的顺序有时候是错乱的，导致当前的计数 count 无法解密当前收到的数据包。vmess 协议中，若数据流使用 aead 加密，每个数据包都会使用一个自增的 count 作为 iv 的一部分进行数据包加密，所以必须要确保数据包的顺序是严格按照 count 自增的顺序发送。
通过阅读 clash 内核的代码，发现 clash 会启动多个 goroutine 进行处理 udp 数据包：
https://github.com/Dreamacro/clash/blob/baf03b81e36e3c5d8b9a370ebb82dd2b25b4a58d/tunnel/tunnel.go#L107
这就直接导致了 aeadWriter 的 Write 函数可能会被并发调用，进而引发数据包错乱的问题：
https://github.com/Dreamacro/clash/blob/baf03b81e36e3c5d8b9a370ebb82dd2b25b4a58d/component/vmess/aead.go#L24
经测试，在 Write 函数中加入锁之后，数据包的顺序不再错乱了。
我的 pr 是最简单粗暴的解决方案，不一定好，只是起到抛砖引玉的作用，在 clash 内核中的其它协议实现可能也存在类似的问题，我个人对 clash 内核的设计还不怎么熟悉，希望有大佬能够彻底解决这个问题。
> fix vmess aead writer udp issue

- component/process/process_freebsd_amd64.go
FreeBSD 13 has been released: [https://www.freebsd.org/releases/13.0R/announce](https://www.freebsd.org/releases/13.0R/announce).
Luckily the offsets stay same as 12.x
Tested on FreeBSD 12.2 & FreeBSD 13.
> Chore: PROCESS-NAME support freebsd 13, fix panic on unsupported platforms

- component/snell/pool.go
This bug can be reproduced using [open-snell](https://github.com/icpz/open-snell) and [hey](https://github.com/rakyll/hey).
*hey is a tiny program that sends some load to a web application.*
---
snell server listens at port 5678.
```ini
[snell-server]
listen = 0.0.0.0:5678
psk = psk
obfs = http
```
clash listens at port 9999 with a default outbound to snell server.
```yaml
port: 9999
proxies:
- name: PROXY
obfs-opts:
host: docs.aws.amazon.com
mode: http
psk: psk
server: 127.0.0.1
port: 5678
type: snell
version: 2
rules:
- MATCH,PROXY
```
use hey to send some http request via clash
```bash
./hey -disable-keepalive -x http://127.0.0.1:9999 https://www.qq.com
```
```
Status code distribution:
[200]	49 responses
Error distribution:
[124]	Get "https://www.qq.com": EOF
[1]	Get …
```
> Fix: io timeout when snell reuse connection

- adapters/provider/fetcher.go
修正了 本地初始化失败时 回退到从远程下载文件后 不会写入文件的问题
> Fix: should write file if provider initialize from HTTP

- Makefile
Let clash can run on Raspi with FreeBSD.
> Feature: add freebsd arm64 to Makefile

- adapters/outboundgroup/urltest.go
provider 更新时，如果之前选中的最快节点已经被移除，需要进行移除，否者可能还是会返回已经移除的节点
> Fix: skip deleted node from url-test group

- component/trie/domain.go
- config/config.go
- dns/resolver.go
- hub/executor/executor.go
Sometimes we need clash lookup domains via specific nameservers. Here is an example configuration:
```yaml
dns:
enable: true
listen: '0.0.0.0:53'
assign-nameserver:
'www.baidu.com': '114.114.114.114'
'+.internal.crop.com': '10.0.0.1'
```
This feature may resolve issues like https://github.com/Dreamacro/clash/issues/1376 .
It seems that we need a more appropriated term here, instead of `assign-nameserver`.
> Feature: lookup domain through assigned nameserver

- hub/route/configs.go
让reload从curl触发时更简单一些，reload时往往不关心之前配置文件放在哪里，只要直接使用启动时指定的配置文件就可以了。
e.g. `curl -v -X PUT -d '{}' 'http://127.0.0.1:4413/configs'`
> reload配置时path为空则用默认值

- dns/server.go
大部分公共DNS服务器都启用了DNS域名压缩，而 miekg/dns 默认没有启用压缩，从而导致转发的DNS包体积发生膨胀。
该问题会导致某些客户端在解析含有大量CNAME记录的域名时出现问题。（例如用 Go 默认的 resolver 解析 `pcqp03pf-my.sharepoint.com`）
> Fix: enable DNS message compression

- transport/vmess/websocket.go
After #1505 is merged and #1473 is closed, add xray's ws-0rtt path scheme support and can work with v2ray-plugin without addition change.
based on : [xray's websocket document](https://xtls.github.io/config/transports/websocket/)
> [Feature] support xray's ws-0rtt path scheme

- adapter/inbound/http.go
- listener/http/client.go
应该检查 http.Client.DialContext 的入参 (
> Fix: should not trust address of http.Client

- listener/http/proxy.go
- listener/http/utils.go
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/407
https://tools.ietf.org/html/rfc7235#section-3.2
According to above, "Proxy-Authenticate" header should not be remove when
the status is proxy authentication required.
This may fix Chrome SwitchyOmega directly use a https proxy include authentication.
Related to [1443](https://github.com/Dreamacro/clash/pull/1443) and [issuecomment-916173170](https://github.com/Dreamacro/clash/pull/1584#issuecomment-916173170)
> Fix: http/https proxy authentication

- adapter/outbound/http.go
- adapter/outbound/shadowsocks.go
- adapter/outbound/shadowsocksr.go
- adapter/outbound/snell.go
- adapter/outbound/socks5.go
- adapter/outbound/trojan.go
- adapter/outbound/vmess.go
Hi,
I found that the routing-mark option under shadowsocks doesn't make any effect. This pull request fixed it.
> fix routing-mark option doesn't work on shadowsocks

- common/structure/structure.go
When processing data through `json.Unmarshal`, `port` thinks it is `float64`, which causes the parsing node to report an error
> When processing data through `json.Unmarshal`, `port` thinks it is `float64`, which causes the parsing node to report an error

- listener/redir/tcp_linux.go
Fix getorigdst cannot get origin destination address in MIPS64 (big-endian) in linux. 
Because unsafe.Sizeof returns uintptr (8 byte) and kernel use int (4 byte) to receive data size, in big-endian the value will be truncated to zero, kernel check data length failed with EINVAL.
> Fix: convert size to unit32 in function getoridst to fix EINVAL on mips64

- Dockerfile
- Makefile
* Instead of separating the Go module download, we could remove this and just use a cache mount for ```/go/pkg/mod```
* ```COPY``` will create an extra layer in the container image which slows things down and uses extra disk space. This can be avoided by using ```RUN --mount``` and bind mounting from the build context, from a stage, or an image.
* add a cross compiling targets to the Dockerfile: ```TARGETOS``` & ```TARGETARCH```
* add ```BUILDPLATFORM``` -> matches current machines CPU architecture (eg. linux/amd64)
* go build reduced by 1/3 and the image size has been reduced by 1/4 (22MB->16MB)
Useful links:
https://www.docker.com/blog/containerize-your-go-developer-environment-part-1/
https://www.reddit.com/r/golang/comments/q7zppz/docker_cache_for_dependencies/ …
> refactor: update Dockerfile

- adapter/outboundgroup/common.go
- adapter/outboundgroup/urltest.go
- adapter/provider/provider.go
- constant/provider/interface.go
In `URLTest`, `fastSingle` will cache the result in 10s. If there are many request call `fast(false)`, maybe the `u.proxies()` inside will never be called by `true`.
> Fix: a shared fastSingle.Do() may cause providers untouched

- adapter/outbound/http.go
- adapter/outbound/shadowsocks.go
- adapter/outbound/shadowsocksr.go
- adapter/outbound/snell.go
- adapter/outbound/socks5.go
- adapter/outbound/trojan.go
- adapter/outbound/util.go
- adapter/outbound/vmess.go
follow this link: https://stackoverflow.com/a/42703862
>  If you pass any parameters to the defer func (like the 2nd defer function above), those parameters are evaluated when the defer function is deferred, not when they are executed.
> fix: safeConnClose not working

- config/config.go
- dns/resolver.go
- hub/executor/executor.go
Environments like `docker` and `kubernetes` often have default DNS resolvers that contain [search domains](https://en.wikipedia.org/wiki/Search_domain) that make service discovery easier. For example, within a single Kubernetes namespace, I can reach a Postgres pod at `http://postgres` without needing to specify the fully qualified name. For example:
```
$ cat /etc/resolv.conf
nameserver 172.10.0.10
search my-namespace.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```
Unfortunately, there is no way to preserve this configuration when using `fake-ip` in `clash` today. If the `search` field is left in the `/etc/resolv.conf` and the `resolv.conf` is changed so that all DNS queries go to clash's resolver at `0.0.0.0:53`, **all** queries will have …
> Feature: add support for search domains

- dns/resolver.go
- dns/util.go
The following code uses the TTL of the very first record, as the whole TTL of the response,
https://github.com/Dreamacro/clash/blob/df61a586c9df496c2ab71790534b0cab5d9e47ba/dns/util.go#L28-L33
and these codes further use the previous TTL as the TTL of each entry in answers.
https://github.com/Dreamacro/clash/blob/df61a586c9df496c2ab71790534b0cab5d9e47ba/dns/util.go#L42-L55
This will cause issue when the first answer in the DNS message is greater than the later record.
For example, in the first DNS query
```bash
╰─❯ dog epdg.epc.mnc260.mcc310.pub.3gppnetwork.org A @openwrt.lan
CNAME epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.     5h49m11s   "epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org."
A epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org.      17s   208.54.39.163
```
And the second cached …
> Fix: Adjust DNS TTL values based on minimum value

- tunnel/connection.go
When using vmess + fake-ip, after receiving the first UDP response, PacketConn's internal address will be rewritten to fake-ip, causing all subsequent sending operations to return "ErrUDPRemoteAddrMismatch".
```diff
diff --git a/tunnel/connection.go b/tunnel/connection.go
index 0614603..c220908 100644
--- a/tunnel/connection.go
+++ b/tunnel/connection.go
@@ -39,7 +39,7 @@ func handleUDPToLocal(packet C.UDPPacket, pc net.PacketConn, key string, oAddr,
return
}
-               fromUDPAddr := from.(*net.UDPAddr)
+               fromUDPAddr := *from.(*net.UDPAddr)
if fAddr.IsValid() {
fromAddr, _ := netip.AddrFromSlice(fromUDPAddr.IP)
fromAddr = fromAddr.Unmap()
@@ -48,7 +48,7 @@ func handleUDPToLocal(packet C.UDPPacket, pc net.PacketConn, key string, oAddr,
}
}
-               _, err = …
```
> Fix: PacketConn's internal remote address is overwritten

- docs/premium/script.md
> Docs: fix typo in script.md

- .golangci.yaml
- constant/metadata.go
- constant/rule.go
- log/log.go
- rule/domain.go
- rule/domain_keyword.go
- rule/domain_suffix.go
- rule/final.go
- rule/geoip.go
- rule/ipcidr.go
- rule/ipset.go
- rule/parser.go
- rule/parser_test.go
- rule/port.go
- rule/process.go
- tunnel/tunnel.go
There are no exported string type constants for `RuleType` and the rule types from configuration files right now, developers often needs to explicitly write out and enumerate all the possible rule type, and other iota type when integration with clash and process with configuration files, therefore I added the standalone `RuleConfig` type alone with all the currently supported rule types that exported for better API and DX.
- Added `RuleConfig` type and all the enums.
- Added compile-time interface check as this is part of the best practice that mentioned by Uber Golang Guide. [References](https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance)
- Added `exhaustive` linter to check whether all the enums are presented in switch branches.
> Refactor(constant): added rule string enums in configs as RuleConfig for better outside integrations

- .github/workflows/release.yml
- .github/workflows/test.yaml
- Makefile
- rule/parser_test.go
1. It looks like the previous merged PR cause the GitHub Actions `Get dependencies, run test` step in `build` job for `Release` workflow failed to run, and this repository is missing a unit test and build test CI when collaborate within Pull Request.
2. In order to properly fix the failed test and or help the collaborative developers get the insights of their committed codes with CI/CD provided GitHub Actions, this Pull Request proposed to setup a standalone CI that triggers on `push` and `pull_request`.
> Chore: added a new test CI to run unit test and build test for Pull Requests

- dns/resolver.go
- dns/util.go
1. DNS NCACHE was not correctly implemented.
2. OPT RRs must not be cached or forwarded.
Closes #2889.
---
Open question: Should we reintroduce the hack of bypassing caches for ACME challenge RRs?
https://github.com/Dreamacro/clash/blob/c1d027d6d1e6b9db7205ad74a4554c96822110bb/dns/util.go#L37-L41
I'm not sure why we would need this workaround. It appears that the RRs will be cached by the upstream servers regardless.
> Fix: DNS NCACHE TTL and OPT RRs
