adapters/outbound/shadowsocks.go
adapters/outbound/socks5.go
adapters/outbound/vmess.go

如果是ipv6,直接用sprintf会出问题。正常的ipv6合并应该是[::]:80

Fix: use JoinHostPort for ipv6

---

adapters/outbound/socks5.go

Feature: socks5 auth support

---

Makefile

makefile add freebsd support

---

component/vmess/conn.go
component/vmess/vmess.go

fix [clash_for_windows_pkg/issues/65](https://github.com/Fndroid/clash_for_windows_pkg/issues/65)

Fix: block writing when use vmess

---

Makefile
constant/version.go
main.go

#147 
```bash
$./bin/clash-linux-amd64 -v
Clash v0.12.0-22-g87a7514 linux amd64 Thu 21 Mar 11:37:19 UTC 2019
```

Feat: add version option

---

README.md

I had to ask people in the Telegram group to check the API docs, so I think adding this to the README will be very useful.

Add GitBook link in README.md

---

Makefile
README.md

fix misspelling

---

dns/server.go

https://github.com/Dreamacro/clash/commit/0d4a999707da2ec0c989aa3fe2b8faff5950340c
dns return origin ttl when hit cache

fix fake ip dns ttl

---

config/config.go

Fix: checking target is valid in rules

---

README.md

fixes https://github.com/Dreamacro/clash/issues/237

use lower case cipher format

---

config/config.go

fixes https://github.com/Dreamacro/clash/issues/235

fix the yaml/yml compatibility issue

---

README.md
config/config.go
hub/executor/executor.go
hub/route/configs.go
proxy/listener.go

fixes https://github.com/Dreamacro/clash/issues/135

Feature: support customizing bind-address when allow-lan is true

---

tunnel/connection.go

https://tools.ietf.org/html/rfc7231#section-6.2.1
This is just a temporary fix for it:
1. remove `Expect: 100-continue` from request header
2. if got `100 Continue` by accident, just read another request
To fix it completely, we must(but no need unless you care about the wait time of 100-contine):
1. read only headers and check `Expect: 100-continue`, if not found, just continue to read body and send the whole request and skip all steps followed
2. send headers without data body
3. read response with status code `100 Continue`, if timeout or got incorrect status code, close the connection with certain status code returned (skip step 4)
4. read data body, send it and read response

Fix: HTTP Status Code `100 Continue` support"

---

tunnel/connection.go

1. if `Connection: Keep-Alive` is set in header, do not break loop. Otherwise http client side may think the connection was keep-alive but reset by remote http server
2. if client sends keep-alive, follow its request even there is no data reply
this is just another bug found in my .NET/Mono WebClient program

Fix: don't close connection on status `100 Continue` and header `Proxy-Connection: Keep-Alive`

---

adapters/outbound/base.go
adapters/outbound/selector.go
config/config.go
config/utils.go

Fix:  Handle parsing error in proxyGroupsDagSort

---

README.md
config/config.go
dns/filters.go
dns/resolver.go
hub/executor/executor.go

This allows us to tell clash to give up poisoned DNS results like 243.185.187.39

 Feature: DNS fallback-ip configuration

---

adapters/outbound/urltest.go
common/picker/picker.go
common/picker/picker_test.go
dns/resolver.go
hub/route/proxies.go

Optimize time takes to get fastest node especial when startup and the first node is not alive.

optimize time takes to get fastest node

---

proxy/listener.go

ref: https://github.com/Dreamacro/clash/pull/341

fix: UDP socks listener not stop with zero port

---

adapters/outbound/util.go
common/observable/observable_test.go
component/v2ray-plugin/mux.go
dns/util.go

* Rewrite if-else statements as switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
* Some assignments simplified by using assignment operators.

Some code improvements

---

config/config.go

用于解决类似 https://github.com/Dreamacro/clash/issues/465 的 问题 (
虽然这样只能 直接链接的应用调用
但是 万一有生之年的 event api 呢 (不是

[Feature] Export Raw Config

---

adapters/provider/parser.go
config/config.go
constant/path.go

Fix constant Path `Reslove` typo

Chore: fix typo

---

common/sockopt/reuseaddr_linux.go
common/sockopt/reuseaddr_other.go
dns/server.go
proxy/redir/udp_linux.go
proxy/socks/udp.go

[Fix] Set SO_REUSEADDR for UDP listeners on linux

---

adapters/provider/vehicle.go

Copy from https://github.com/Kr328/ClashForAndroid/commit/c5104c241a1a38f3d46339250b6f3d7bd96937e9

Improve: add basic auth support for provider URL

---

adapters/inbound/socket.go
proxy/redir/tcp.go
proxy/socks/tcp.go

Remove unused parameter netType

Fix: remove unused parameter netType

---

hub/hub.go
main.go

Feature: add command-line options to override `external-controller`, `secret` and `external-ui` (#531)

---

dns/resolver.go

Fix: should put ip to host mapping if isIPRequest == true

---

rules/base.go
rules/process_linux.go
rules/process_other.go

为 Linux 添加 PROCESS-NAME 规则
TODO:

Feature: add PROCESS-NAME rule for linux

---

rules/process_linux.go

Improve: check uid on linux process search & fix typo

---

README.md

make every item in TODO list has the same style

change the appearance of "Event API" item

---

adapters/outbound/base.go

`Proxy`对象会被多个连接并发使用，加上独立的URLTest的goroutine，实际上`alive`这个变量是在并发读写的，因此需要用atomic保护起来，保证修改对其它goroutine都是可见的。

对alive变量进行并发保护

---

rules/process_darwin.go

+ Fix: xsocket_n.so_last_pid has native byte order
+ Improve: simplify pcblist parsing, reduce magic numbers

Improve: simplify darwin process searching, read pid as native endian uint32

---

component/snell/snell.go

There is one byte error code before the length of message.
https://github.com/icpz/snell-server-reversed/blob/master/README.v1.md#s-to-c

Fix: handle snell server reported error message properly

---

go.mod
rules/process_other.go
rules/process_windows.go

只在虚拟机里 (windows 10 1909 amd64) 测试通过- -
大佬们帮忙测试一下其它版本的系统？

Feature: PROCESS-NAME for windows

---

adapters/outboundgroup/urltest.go

might fix https://github.com/Dreamacro/clash/issues/851

chore: adjust tolerance logic

---

config/config.go
dns/middleware.go
dns/resolver.go
hub/executor/executor.go

reimplement https://github.com/Dreamacro/clash/pull/852

Feature: dns server should lookup hosts

---

Makefile

Add Windows ARM32 build for Windows 8 RT and Windows 10 AArch64

Add Windows ARM32 build

---

tunnel/manager.go
tunnel/tracker.go

使用由硬件实现的 atomic 修改统计数据 理论上应该会比 chan 具有更好的性能

Feature: use atomic for connection statistic

---

tunnel/manager.go

Chore: merge duplicate ticker

---

adapters/outbound/snell.go
component/pool/pool.go
component/pool/pool_test.go
component/snell/cipher.go
component/snell/pool.go
component/snell/snell.go
go.mod
go.sum

#920 
base on https://github.com/icpz/snell-server-reversed and https://github.com/icpz/open-snell

Feature: support snell v2 (without connection reuse)

---

Makefile

ref: https://github.com/golang/go/issues/34186

Make builds reproducible

---

component/nat/table.go
tunnel/tunnel.go

fix https://github.com/Dreamacro/clash/issues/1039

Fix: tunnel UDP race condition

---

adapters/outbound/base.go
common/observable/observable_test.go
common/singledo/singledo_test.go
go.mod
go.sum
tunnel/manager.go
tunnel/tracker.go

fix https://github.com/Dreamacro/clash/issues/1041 by using `go.uber.org/atomic`

Fix: tunnel manager & tracker race condition

---

adapters/provider/healthcheck.go

现有的方法无论代理是否全部完成测试 都会等待 `defaultURLTestTimeout`
换用 WaitGroup 后能在代理全部完成测试后立即返回

Fix: health checks should return immediately if completed

---

adapters/provider/vehicle.go
component/vmess/h2.go
component/vmess/websocket.go
tunnel/connection.go

Close any http body  that are not turned off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreamacro/clash/1154)

[bugfix]: close http body.

---

adapters/outbound/socks5.go

类似gost、v2ray的socks5服务端在响应UDP代理请求时会返回`0.0.0.0`，接着直接使用服务端地址去请求有时可以解决一些NAT带来的错误UDP Bind Address问题。
虽然在RFC里没有定义这类规范，但是可以拓展支持一下。

Feature: Support unspecified UDP bind address

---

component/ssr/protocol/auth_chain_a.go

Fix #1019 and fix #1058 and some potential problems.
Thanks https://github.com/v2rayA/shadowsocksR/commit/b2a7be4ef7cf8c48d42dea90476102ea371fb8b0#commitcomment-45520839

Bug fixes for auth_chain_[ab] protocol

---

Dockerfile

Signed-off-by: Junjie Yuan <yuan@junjie.pro>

fix docker label

---

config/initial.go

jsdelivr CDN is user friendly in China mainland.

Use jsdelivr CDN for Country.mmdb

---

config/config.go

Fix: should not unmarshal to pointer

---

.github/workflows/docker.yml

Add linux/arm/v6 for the container image

---

adapter/adapter.go
adapter/inbound/util.go
adapter/outbound/util.go
adapter/outbound/vmess.go
adapter/outboundgroup/util.go
constant/metadata.go
rule/domain.go
rule/domain_keyword.go
rule/domain_suffix.go
tunnel/tunnel.go

Remove unnecessary `AddrType` field.
Need to evaluate this change together.

Change: remove AddrType on Metadata

---

README.md

see #https://github.com/badges/shields/issues/8671

fix broken build badge

---

.github/ISSUE_TEMPLATE/bug_report_en.yml
.github/ISSUE_TEMPLATE/bug_report_zh.yml

提交 Issue 的时候发现模板有问题，clash 不能识别全大写的 DEBUG。

Chore: fix ISSUE_TEMPLATE (DEBUG -> debug)

---

adapter/outboundgroup/parser.go
adapter/provider/provider.go
go.mod
go.sum

替换正则库为github.com/dlclark/regexp2

---

dns/util.go

Regarding DNS cache, it's advisable to not rely on the TTL values mentioned in the Ns and Extra sections. Otherwise, any DNS queries that do not yield any results (such as for non-existent.example.com) will be accidentally cached.
The need for the ACME challenge hack has been eliminated and as such, it has been removed.

Fix: DNS cache max-age

---

docs/premium/tun-device.md
docs/zh_CN/premium/tun-device.md

doc: update tun-device.md

---

docs/premium/script.md

the raw code in the first code block will cause error

fix example error
